---
- name: 1. Corrigir Sources List (Forçar Mirror Oficial)
  copy:
    dest: /data/data/com.termux/files/usr/etc/apt/sources.list
    content: |
      deb https://packages.termux.dev/apt/termux-main stable main
    mode: '0644'

- name: 2. Atualizar Repositórios
  shell: "pkg update -y && pkg upgrade -y"
  ignore_errors: yes

- name: 3. Instalar Pacotes Essenciais (Git, SSH, Htop)
  shell: "pkg install -y git openssh htop screen vim"
